### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by VascoSch92** [SHREYAS1188/vector_python_package#2]
Is the package still maintained?

**Comment by SHREYAS1188** [comment]
> Is the package still maintained?

Hello @VascoSch92 ,

Yes the package is maintained and updates are done as and when required.

**Comment by VascoSch92** [comment]
Never thinked to implement tests?

**Comment by SHREYAS1188** [comment]
> Never thinked to implement tests?

I Have checked but not updated on github.

**Comment by SHREYAS1188** [comment]
I will be updating it, thanks for mentioning that out @VascoSch92 👍

**Comment by SHREYAS1188** [comment]
@VascoSch92 the test file is created now, thanks for your input on creating those.

Please feel free to suggest any further improvements

Thank You
